version: build{build}

branches:
    except:
    - project/travis

environment:
    matrix:
    - name: win32
      platform: amd64_x86
      qt:msvc2017
      
build_script: 
  - call "C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\vcvarsall.bat" x86_amd64
  - set QTDIR=C:\Qt\5.12.0\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - qmake
  - nmake & exit 0
